/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aditya;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class MyEmpFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyEmpFrame
     */
    private Connection con ;
    private PreparedStatement ps;
    public MyEmpFrame() {
        initComponents();
        connectDB();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblempno = new javax.swing.JLabel();
        txtempno = new javax.swing.JTextField();
        lblempname = new javax.swing.JLabel();
        txtempname = new javax.swing.JTextField();
        lblsalary = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel1.setText("Emp Management App");

        lblempno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempno.setText("EMPNO");

        txtempno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblempname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblempname.setText("EMPNAME");

        txtempname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblsalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsalary.setText("SALARY");

        txtsalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setText("ADD RECORDS");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnShow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShow.setText("SHOW RECORDS");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblempno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblempname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtempno)
                    .addComponent(txtempname)
                    .addComponent(txtsalary)
                    .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblempno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtempno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblempname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtempname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        txtaResult.setColumns(20);
        txtaResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtaResult.setRows(5);
        jScrollPane1.setViewportView(txtaResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        boolean result = validateInputs();
        if(!result) // if(result==false) //
        {
            JOptionPane.showMessageDialog(null,"Please Input All the Values");
            return;
        }
        try{
            String empno = txtempno.getText();
            String empname = txtempname.getText();
            String empsalary = txtsalary.getText();
            int eno = Integer.parseInt(empno);
            double esal = Double.parseDouble(empsalary);
            ps.setInt(1, eno);
            ps.setString(2, empname);
            ps.setDouble(3,esal);
            int ans =ps.executeUpdate();
            if(ans==1)
            {
                JOptionPane.showMessageDialog(null, "Record added successfully to the db");
                txtempno.setText("");
                txtempname.setText("");
                txtsalary.setText("");
                txtempno.requestFocus();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Record Not Added , Try Later!");
            }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Please Input Digits for Empno and sal!");
            ex.printStackTrace();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "DB Error!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
       try
       {
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("Select * from employee order by empno");
           StringBuffer sb = new StringBuffer();
           while(rs.next())
           {
               int eno=rs.getInt(1);
               String ename=rs.getString(2);
               Double sal = rs.getDouble(3);
               sb.append(eno+"\t"+ename+"\t"+sal+"\n");
               
           }
           txtaResult.setText(sb.toString());
       }
       catch(SQLException ex)
       {
            JOptionPane.showMessageDialog(null, "DB Error!");
            ex.printStackTrace();
       }
    }//GEN-LAST:event_btnShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyEmpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnadd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblempname;
    private javax.swing.JLabel lblempno;
    private javax.swing.JLabel lblsalary;
    private javax.swing.JTextArea txtaResult;
    private javax.swing.JTextField txtempname;
    private javax.swing.JTextField txtempno;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables

    private void connectDB() {
       try{
           Class.forName("oracle.jdbc.OracleDriver"); // Load & register the jdbc driver //
           con = DriverManager.getConnection("jdbc:oracle:thin:@//AdityaKumar:1521/xe","myproject","java");
           ps=con.prepareStatement("Insert into employee values(?,?,?)");
           JOptionPane.showMessageDialog(null, "Successfully connected to DB");  
       }
       catch(Exception ex)
       {
         JOptionPane.showMessageDialog(null,"Error in DB "+ex);   
         ex.printStackTrace(); 
       }
    } 

    private boolean validateInputs() {
        if(txtempname.getText().isEmpty() || txtempno.getText().isEmpty() || txtsalary.getText().isEmpty())  //Chaining//
            return false;
        else 
            return true;
    }
}
